const mockData = [
    {
      subjectType: 1,
      subjectTypeName: "加盟门店",
      franchiseesTypeList: [
        {
          id: 44,
          franchiseeName: "白月",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624531079000,
          updateTime: 1643082437000,
          remark: "广东直营，有银行卡",
          userIdType: null
        },
        {
          id: 45,
          franchiseeName: "吴伟",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624531081000,
          updateTime: 1643082404000,
          remark: "福建直营，有银行卡",
          userIdType: null
        },
        {
          id: 46,
          franchiseeName: "张三",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624531082000,
          updateTime: 1643082475000,
          remark: "海南直营，无银行卡",
          userIdType: null
        },
        {
          id: 47,
          franchiseeName: "小明同学",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624537203000,
          updateTime: 1625047865000,
          remark: null,
          userIdType: null
        },
        {
          id: 48,
          franchiseeName: "小茗同学",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624589798000,
          updateTime: 1625047865000,
          remark: null,
          userIdType: null
        },
        {
          id: 49,
          franchiseeName: "夏明",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624589971000,
          updateTime: 1625047865000,
          remark: null,
          userIdType: null
        },
        {
          id: 50,
          franchiseeName: "小小",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624590193000,
          updateTime: 1625047865000,
          remark: null,
          userIdType: null
        },
        {
          id: 51,
          franchiseeName: "小块",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624591350000,
          updateTime: 1625047865000,
          remark: null,
          userIdType: null
        },
        {
          id: 52,
          franchiseeName: "独家发售",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624591531000,
          updateTime: 1625047865000,
          remark: null,
          userIdType: null
        },
        {
          id: 53,
          franchiseeName: "搭建",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624591584000,
          updateTime: 1625047865000,
          remark: null,
          userIdType: null
        },
        {
          id: 55,
          franchiseeName: "白星",
          withdrawalMobile: "18301926052",
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624846292000,
          updateTime: 1650357072000,
          remark: "安徽加盟，有银行卡",
          userIdType: null
        },
        {
          id: 56,
          franchiseeName: "接口",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624846335000,
          updateTime: 1643082573000,
          remark: "四川重庆加盟，有银行卡",
          userIdType: null
        },
        {
          id: 57,
          franchiseeName: "小红",
          withdrawalMobile: "18301926052",
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624850737000,
          updateTime: 1646802884000,
          remark: "湖南湖北直营，有银行卡",
          userIdType: null
        },
        {
          id: 62,
          franchiseeName:
            "啦啦金.sadfgahh¥&%&*##嘎嘎哈哈哈哈沙发发发敢发钱诶飞机为 i 日发布啦的发发卡",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624947791000,
          updateTime: 1625047865000,
          remark: null,
          userIdType: null
        },
        {
          id: 67,
          franchiseeName: "啦啦。jin*（&",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1625025584000,
          updateTime: 1625047865000,
          remark: null,
          userIdType: null
        },
        {
          id: 69,
          franchiseeName:
            "金啦啦嘎嘎阿哈哈哈返回的发发呆嘎嘎金啦啦嘎嘎阿哈哈哈返回的发发呆回的发发呆回的发发呆回的发发呆111",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1625040770000,
          updateTime: 1625047865000,
          remark: null,
          userIdType: null
        },
        {
          id: 70,
          franchiseeName: "接决方法",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1625048623000,
          updateTime: 1643082747000,
          remark: "无组织门店，有银行卡",
          userIdType: null
        },
        {
          id: 72,
          franchiseeName: "金啦啦",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1625132472000,
          updateTime: 1643082869000,
          remark: "浙江直营，有银行卡",
          userIdType: null
        },
        {
          id: 73,
          franchiseeName: "啦啦金",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1625451306000,
          updateTime: 1643082876000,
          remark: "浙江加盟，有银行卡",
          userIdType: null
        },
        {
          id: 74,
          franchiseeName: "丁丁",
          withdrawalMobile: "13273714873",
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1625451403000,
          updateTime: 1643266410000,
          remark: "福建加盟，有银行卡",
          userIdType: null
        },
        {
          id: 77,
          franchiseeName: "王亚轩",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1626264310000,
          updateTime: 1643082962000,
          remark: "云南，无银行卡",
          userIdType: null
        },
        {
          id: 80,
          franchiseeName: "wuxiang",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1632968848000,
          updateTime: 1632968848000,
          remark: null,
          userIdType: null
        },
        {
          id: 81,
          franchiseeName: "18351956368",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1632969355000,
          updateTime: 1632969355000,
          remark: null,
          userIdType: null
        },
        {
          id: 82,
          franchiseeName: "wuxiang",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1632969507000,
          updateTime: 1632969507000,
          remark: null,
          userIdType: null
        },
        {
          id: 85,
          franchiseeName: "付淑燕",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1632994132000,
          updateTime: 1643082950000,
          remark: "江苏，无银行卡",
          userIdType: null
        },
        {
          id: 87,
          franchiseeName: "许宏杰",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1632994679000,
          updateTime: 1643083259000,
          remark: "广东加盟，有银行卡",
          userIdType: null
        },
        {
          id: 91,
          franchiseeName: "曹实杭",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1632999718000,
          updateTime: 1648894004000,
          remark: "广西加盟，有银行卡",
          userIdType: null
        },
        {
          id: 92,
          franchiseeName: "曹实杭",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1632999744000,
          updateTime: 1648894008000,
          remark: null,
          userIdType: null
        },
        {
          id: 93,
          franchiseeName: "曹实杭3",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1632999745000,
          updateTime: 1648710415000,
          remark: null,
          userIdType: null
        },
        {
          id: 94,
          franchiseeName: "曹实杭4",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1632999746000,
          updateTime: 1648710417000,
          remark: null,
          userIdType: null
        },
        {
          id: 114,
          franchiseeName: "吴晴晴",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1633938513000,
          updateTime: 1643090992000,
          remark: "山西加盟，有银行卡",
          userIdType: null
        },
        {
          id: 118,
          franchiseeName: "jyf",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1635156063000,
          updateTime: 1643090960000,
          remark: "山东加盟，无银行卡",
          userIdType: null
        },
        {
          id: 119,
          franchiseeName: "qqq",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1637240925000,
          updateTime: 1643090917000,
          remark: "江西加盟，无银行卡",
          userIdType: null
        },
        {
          id: 120,
          franchiseeName: "qs",
          withdrawalMobile: "18251930877",
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1637293335000,
          updateTime: 1644895417000,
          remark: "QS等，有银行卡",
          userIdType: null
        },
        {
          id: 123,
          franchiseeName: "奈美芸华有限公司",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1639104456000,
          updateTime: 1643090879000,
          remark: "金额错误，无法提现",
          userIdType: null
        },
        {
          id: 124,
          franchiseeName: "test",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1639364303000,
          updateTime: 1639364303000,
          remark: null,
          userIdType: null
        },
        {
          id: 126,
          franchiseeName: "什么公司",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1639379489000,
          updateTime: 1644550382000,
          remark: "湖南湖北加盟，无银行卡",
          userIdType: null
        },
        {
          id: 128,
          franchiseeName: "测试",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1639380802000,
          updateTime: 1643090822000,
          remark: "河南河北加盟，无银行卡",
          userIdType: null
        },
        {
          id: 130,
          franchiseeName: "好的，恐龙园元",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1639387190000,
          updateTime: 1643090785000,
          remark: "海南加盟，无银行卡",
          userIdType: null
        },
        {
          id: 131,
          franchiseeName: "小可科技有限公司",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1639392034000,
          updateTime: 1649724998000,
          remark: "贵州加盟，有银行卡",
          userIdType: "03"
        },
        {
          id: 132,
          franchiseeName: "宋小",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1639447610000,
          updateTime: 1643090627000,
          remark: "江西直营，有银行卡",
          userIdType: null
        },
        {
          id: 133,
          franchiseeName: "钱莹副食品商贸有限公司",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1639447748000,
          updateTime: 1643102586000,
          remark: "山东直营，无银行卡",
          userIdType: null
        },
        {
          id: 134,
          franchiseeName: "邱爽",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1641293449000,
          updateTime: 1643091397000,
          remark: "天津加盟，无银行卡",
          userIdType: null
        },
        {
          id: 135,
          franchiseeName: "嘻嘻",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1641366486000,
          updateTime: 1641464147000,
          remark: "OK",
          userIdType: null
        },
        {
          id: 136,
          franchiseeName: "裴昆昆",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1642408929000,
          updateTime: 1642408929000,
          remark: null,
          userIdType: null
        },
        {
          id: 140,
          franchiseeName: "ERP测试",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643099371000,
          updateTime: 1647833751000,
          remark: "ERP",
          userIdType: null
        },
        {
          id: 141,
          franchiseeName: "ERP测试",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643099882000,
          updateTime: 1647833752000,
          remark: "ERP-对公账户",
          userIdType: null
        },
        {
          id: 142,
          franchiseeName: "ERP测试",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643100030000,
          updateTime: 1647833753000,
          remark: "ERP测试-test2022",
          userIdType: null
        },
        {
          id: 147,
          franchiseeName: "o(╥﹏╥)o",
          withdrawalMobile: "18251930877",
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643189138000,
          updateTime: 1647941584000,
          remark: null,
          userIdType: null
        },
        {
          id: 150,
          franchiseeName: "在市谋",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643189140000,
          updateTime: 1643266371000,
          remark: null,
          userIdType: null
        },
        {
          id: 152,
          franchiseeName: "七七七",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643190956000,
          updateTime: 1649347691000,
          remark: null,
          userIdType: null
        },
        {
          id: 162,
          franchiseeName: "BOBO",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1646041900000,
          updateTime: 1646041900000,
          remark: null,
          userIdType: null
        },
        {
          id: 163,
          franchiseeName: "测试cwb",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1646891007000,
          updateTime: 1647934502000,
          remark: null,
          userIdType: null
        },
        {
          id: 164,
          franchiseeName: "qs",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1647497758000,
          updateTime: 1647497758000,
          remark: "测试",
          userIdType: null
        },
        {
          id: 165,
          franchiseeName: "qs",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1647510527000,
          updateTime: 1647944228000,
          remark: null,
          userIdType: null
        },
        {
          id: 166,
          franchiseeName: "陈伟彬",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1647852924000,
          updateTime: 1647935717000,
          remark: null,
          userIdType: null
        },
        {
          id: 167,
          franchiseeName: "庄珊",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1648089179000,
          updateTime: 1648878545000,
          remark: "测试-加盟门店",
          userIdType: null
        },
        {
          id: 174,
          franchiseeName: "庄珊",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1648890665000,
          updateTime: 1648890665000,
          remark: "测试加盟商2",
          userIdType: null
        },
        {
          id: 181,
          franchiseeName: "庄珊",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649229256000,
          updateTime: 1649229256000,
          remark: "测试账号",
          userIdType: null
        },
        {
          id: 187,
          franchiseeName: "庄珊",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649410746000,
          updateTime: 1649411271000,
          remark: "测试",
          userIdType: null
        },
        {
          id: 198,
          franchiseeName: "宋小",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649723191000,
          updateTime: 1649723191000,
          remark: null,
          userIdType: null
        },
        {
          id: 199,
          franchiseeName: "全渠道",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649723542000,
          updateTime: 1649723542000,
          remark: null,
          userIdType: null
        },
        {
          id: 200,
          franchiseeName: "汝棠皓",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649723543000,
          updateTime: 1649723543000,
          remark: null,
          userIdType: null
        },
        {
          id: 202,
          franchiseeName: "小宇",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649731685000,
          updateTime: 1649731685000,
          remark: null,
          userIdType: "02"
        },
        {
          id: 204,
          franchiseeName: "5234ff",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649733734000,
          updateTime: 1649733734000,
          remark: "555",
          userIdType: "03"
        },
        {
          id: 208,
          franchiseeName: "75gdf",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649737253000,
          updateTime: 1649737253000,
          remark: "666666666666666",
          userIdType: "03"
        },
        {
          id: 209,
          franchiseeName: "888888jjjjj",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649737629000,
          updateTime: 1649737629000,
          remark: "333",
          userIdType: "03"
        },
        {
          id: 210,
          franchiseeName: "22222ddd",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649738322000,
          updateTime: 1649738322000,
          remark: null,
          userIdType: "03"
        },
        {
          id: 211,
          franchiseeName: "42fe",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649738717000,
          updateTime: 1649738717000,
          remark: null,
          userIdType: null
        },
        {
          id: 212,
          franchiseeName: "876hh",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649738787000,
          updateTime: 1649738787000,
          remark: null,
          userIdType: null
        },
        {
          id: 213,
          franchiseeName: "32fsd",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649738813000,
          updateTime: 1649738813000,
          remark: null,
          userIdType: "03"
        },
        {
          id: 214,
          franchiseeName: "hdf",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649739635000,
          updateTime: 1649739635000,
          remark: null,
          userIdType: "03"
        },
        {
          id: 215,
          franchiseeName: "hdf",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649740449000,
          updateTime: 1649740449000,
          remark: null,
          userIdType: "03"
        },
        {
          id: 216,
          franchiseeName: "jh",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649741023000,
          updateTime: 1649741023000,
          remark: "fff",
          userIdType: "03"
        },
        {
          id: 217,
          franchiseeName: "22d",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649741097000,
          updateTime: 1649741097000,
          remark: null,
          userIdType: "03"
        },
        {
          id: 221,
          franchiseeName: "fsdfsdfads",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649741747000,
          updateTime: 1649741747000,
          remark: "55",
          userIdType: "03"
        },
        {
          id: 222,
          franchiseeName: "232132dd",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649742661000,
          updateTime: 1649742661000,
          remark: null,
          userIdType: "03"
        },
        {
          id: 225,
          franchiseeName: "213123123a",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649744641000,
          updateTime: 1649744641000,
          remark: null,
          userIdType: "03"
        },
        {
          id: 226,
          franchiseeName: "hg",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649745633000,
          updateTime: 1649745633000,
          remark: null,
          userIdType: "03"
        },
        {
          id: 228,
          franchiseeName: "汝棠皓",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649745766000,
          updateTime: 1649745766000,
          remark: null,
          userIdType: null
        },
        {
          id: 229,
          franchiseeName: "432dd",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649746397000,
          updateTime: 1650338533000,
          remark:
            "为该角色命名，如管理员、出纳、运营为该角色命名，如管理员、出纳、运营为该角色命名，如管理员、出纳、运",
          userIdType: null
        },
        {
          id: 230,
          franchiseeName: "gsd",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649746737000,
          updateTime: 1649746737000,
          remark: null,
          userIdType: null
        },
        {
          id: 232,
          franchiseeName: "汝棠皓",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649747305000,
          updateTime: 1650258849000,
          remark: null,
          userIdType: null
        },
        {
          id: 237,
          franchiseeName: "全渠道",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649842712000,
          updateTime: 1650249143000,
          remark: null,
          userIdType: null
        },
        {
          id: 240,
          franchiseeName: "全渠道",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1650339838000,
          updateTime: 1650339838000,
          remark: null,
          userIdType: null
        },
        {
          id: 241,
          franchiseeName: "汝棠皓",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1650339838000,
          updateTime: 1650339838000,
          remark: null,
          userIdType: null
        },
        {
          id: 245,
          franchiseeName: "测试",
          withdrawalMobile: null,
          subjectType: 1,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1652444168000,
          updateTime: 1652444168000,
          remark: "1234   567899876     54321",
          userIdType: null
        }
      ]
    },
    {
      subjectType: 2,
      subjectTypeName: "配送中心",
      franchiseesTypeList: [
        {
          id: 34,
          franchiseeName: "白晓",
          withdrawalMobile: null,
          subjectType: 2,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624517175000,
          updateTime: 1649952759000,
          remark: null,
          userIdType: null
        },
        {
          id: 137,
          franchiseeName: "雷云武",
          withdrawalMobile: null,
          subjectType: 2,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643010926000,
          updateTime: 1647941544000,
          remark: null,
          userIdType: null
        },
        {
          id: 139,
          franchiseeName: "七七七",
          withdrawalMobile: null,
          subjectType: 2,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643083924000,
          updateTime: 1647941547000,
          remark: null,
          userIdType: null
        },
        {
          id: 146,
          franchiseeName: "奈美芸华有限公司",
          withdrawalMobile: null,
          subjectType: 2,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643186429000,
          updateTime: 1643186532000,
          remark: "商户测试，可解绑-by qs",
          userIdType: null
        },
        {
          id: 151,
          franchiseeName: "七七七",
          withdrawalMobile: null,
          subjectType: 2,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643190927000,
          updateTime: 1647937406000,
          remark: null,
          userIdType: null
        },
        {
          id: 153,
          franchiseeName: "望江县方超生态渔馆",
          withdrawalMobile: null,
          subjectType: 2,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643192393000,
          updateTime: 1647944079000,
          remark: "白星+望江县方超生态渔馆",
          userIdType: null
        },
        {
          id: 156,
          franchiseeName: "李发元",
          withdrawalMobile: null,
          subjectType: 2,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1644816858000,
          updateTime: 1647938072000,
          remark: "测试环境蔬菜配送中心账户",
          userIdType: null
        },
        {
          id: 158,
          franchiseeName: "lk测试",
          withdrawalMobile: null,
          subjectType: 2,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1644832313000,
          updateTime: 1647941538000,
          remark: "lk测测试试",
          userIdType: null
        },
        {
          id: 172,
          franchiseeName: "庄珊",
          withdrawalMobile: null,
          subjectType: 2,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1648890121000,
          updateTime: 1648890121000,
          remark: "测试配送中心",
          userIdType: null
        },
        {
          id: 175,
          franchiseeName: "曹实杭",
          withdrawalMobile: null,
          subjectType: 2,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1648894062000,
          updateTime: 1649396239000,
          remark: "配送中心",
          userIdType: null
        },
        {
          id: 176,
          franchiseeName: "曹实杭",
          withdrawalMobile: null,
          subjectType: 2,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649211051000,
          updateTime: 1649321209000,
          remark: "~~~~",
          userIdType: null
        },
        {
          id: 182,
          franchiseeName: "庄珊",
          withdrawalMobile: null,
          subjectType: 2,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649230358000,
          updateTime: 1649321603000,
          remark: "测试加盟商2",
          userIdType: null
        },
        {
          id: 190,
          franchiseeName: "小宇",
          withdrawalMobile: null,
          subjectType: 2,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649722213000,
          updateTime: 1649722213000,
          remark: null,
          userIdType: "04"
        },
        {
          id: 236,
          franchiseeName: "汝棠皓",
          withdrawalMobile: null,
          subjectType: 2,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649842612000,
          updateTime: 1650357120000,
          remark: null,
          userIdType: null
        },
        {
          id: 239,
          franchiseeName: "测试0419",
          withdrawalMobile: null,
          subjectType: 2,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1650339789000,
          updateTime: 1650339789000,
          remark: "测试",
          userIdType: null
        }
      ]
    },
    {
      subjectType: 3,
      subjectTypeName: "供应商",
      franchiseesTypeList: [
        {
          id: 138,
          franchiseeName: "qs-test",
          withdrawalMobile: null,
          subjectType: 3,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643016463000,
          updateTime: 1647941772000,
          remark: null,
          userIdType: null
        },
        {
          id: 154,
          franchiseeName: "嘿嘿",
          withdrawalMobile: null,
          subjectType: 3,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643270917000,
          updateTime: 1650003658000,
          remark: "备注备注备注",
          userIdType: null
        },
        {
          id: 173,
          franchiseeName: "庄珊",
          withdrawalMobile: null,
          subjectType: 3,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1648890245000,
          updateTime: 1648890245000,
          remark: null,
          userIdType: null
        },
        {
          id: 191,
          franchiseeName: "星耀科技信息有限公司",
          withdrawalMobile: null,
          subjectType: 3,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649722485000,
          updateTime: 1649722485000,
          remark: null,
          userIdType: "05"
        }
      ]
    },
    {
      subjectType: 4,
      subjectTypeName: "总部",
      franchiseesTypeList: [
        {
          id: 238,
          franchiseeName: "四川路路通生物医药有限责任公司",
          withdrawalMobile: null,
          subjectType: 4,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649842810000,
          updateTime: 1650210633000,
          remark: null,
          userIdType: "02"
        }
      ]
    },
    {
      subjectType: 5,
      subjectTypeName: "结算专户",
      franchiseesTypeList: [
        {
          id: 144,
          franchiseeName: "小可科技-结算专户",
          withdrawalMobile: null,
          subjectType: 5,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643185402000,
          updateTime: 1647936209000,
          remark: "''",
          userIdType: null
        },
        {
          id: 178,
          franchiseeName: "恐龙园~~",
          withdrawalMobile: null,
          subjectType: 5,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649211170000,
          updateTime: 1649211170000,
          remark: null,
          userIdType: null
        },
        {
          id: 205,
          franchiseeName: "王亚轩",
          withdrawalMobile: null,
          subjectType: 5,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649733972000,
          updateTime: 1649751621000,
          remark: "测试2",
          userIdType: null
        },
        {
          id: 231,
          franchiseeName: "gd",
          withdrawalMobile: null,
          subjectType: 5,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649746912000,
          updateTime: 1650258819000,
          remark: null,
          userIdType: "03"
        }
      ]
    },
    {
      subjectType: 6,
      subjectTypeName: "其他",
      franchiseesTypeList: [
        {
          id: 143,
          franchiseeName: "在市谋-总部",
          withdrawalMobile: "18217415860",
          subjectType: 6,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643185285000,
          updateTime: 1650013988000,
          remark:
            "o(╥﹏╥)o该角色命名o(╥﹏╥)o该角色命名o(╥﹏╥)o该角色命名o(╥﹏╥)o该角色命名o(",
          userIdType: null
        },
        {
          id: 145,
          franchiseeName: "在市谋-其他",
          withdrawalMobile: null,
          subjectType: 6,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1643185996000,
          updateTime: 1647936216000,
          remark:
            "哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈",
          userIdType: null
        },
        {
          id: 160,
          franchiseeName: "测试-回归",
          withdrawalMobile: null,
          subjectType: 6,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1645081800000,
          updateTime: 1647939637000,
          remark: "其他",
          userIdType: null
        },
        {
          id: 168,
          franchiseeName: "qiu",
          withdrawalMobile: "18301926052",
          subjectType: 6,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1648092492000,
          updateTime: 1648092647000,
          remark: "测试",
          userIdType: null
        },
        {
          id: 179,
          franchiseeName: "曹实杭",
          withdrawalMobile: null,
          subjectType: 6,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649211198000,
          updateTime: 1649211198000,
          remark: null,
          userIdType: null
        },
        {
          id: 193,
          franchiseeName: "伊万科夫有限公司",
          withdrawalMobile: null,
          subjectType: 6,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649722748000,
          updateTime: 1649722748000,
          remark: null,
          userIdType: "07"
        },
        {
          id: 203,
          franchiseeName: "食亨（上海）科技服务有限公司",
          withdrawalMobile: null,
          subjectType: 6,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649733247000,
          updateTime: 1649733247000,
          remark: "测试",
          userIdType: "03"
        },
        {
          id: 206,
          franchiseeName: "测试",
          withdrawalMobile: null,
          subjectType: 6,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649734241000,
          updateTime: 1649734241000,
          remark: null,
          userIdType: null
        },
        {
          id: 227,
          franchiseeName: "gdsfs",
          withdrawalMobile: null,
          subjectType: 6,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649745670000,
          updateTime: 1650006312000,
          remark: null,
          userIdType: null
        },
        {
          id: 235,
          franchiseeName: "测1",
          withdrawalMobile: null,
          subjectType: 6,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649842556000,
          updateTime: 1649842556000,
          remark: null,
          userIdType: null
        },
        {
          id: 244,
          franchiseeName: "邱爽",
          withdrawalMobile: null,
          subjectType: 6,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1651909378000,
          updateTime: 1651909378000,
          remark: "13234567890",
          userIdType: null
        }
      ]
    },
    {
      subjectType: 7,
      subjectTypeName: "直营门店",
      franchiseesTypeList: [
        {
          id: 33,
          franchiseeName: "在市谋",
          withdrawalMobile: null,
          subjectType: 7,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1624506396000,
          updateTime: 1648876791000,
          remark: "12345",
          userIdType: null
        },
        {
          id: 177,
          franchiseeName: "恐龙园",
          withdrawalMobile: null,
          subjectType: 7,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649211118000,
          updateTime: 1649398078000,
          remark: null,
          userIdType: null
        },
        {
          id: 183,
          franchiseeName: "测试",
          withdrawalMobile: null,
          subjectType: 7,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649300911000,
          updateTime: 1649300911000,
          remark: "测试 直营",
          userIdType: null
        },
        {
          id: 184,
          franchiseeName: "庄珊",
          withdrawalMobile: null,
          subjectType: 7,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649302705000,
          updateTime: 1649327664000,
          remark: "测试",
          userIdType: null
        },
        {
          id: 185,
          franchiseeName: "庄珊",
          withdrawalMobile: null,
          subjectType: 7,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649303236000,
          updateTime: 1649388737000,
          remark: null,
          userIdType: null
        },
        {
          id: 186,
          franchiseeName: "sandra",
          withdrawalMobile: null,
          subjectType: 7,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649312492000,
          updateTime: 1649397958000,
          remark: "测试bug",
          userIdType: null
        },
        {
          id: 189,
          franchiseeName: "小夏",
          withdrawalMobile: null,
          subjectType: 7,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649721860000,
          updateTime: 1649721860000,
          remark: "02",
          userIdType: "02"
        },
        {
          id: 192,
          franchiseeName: "小雷",
          withdrawalMobile: null,
          subjectType: 7,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649722643000,
          updateTime: 1649939088000,
          remark: null,
          userIdType: "06"
        },
        {
          id: 220,
          franchiseeName: "小可科技有限公司",
          withdrawalMobile: null,
          subjectType: 7,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649741737000,
          updateTime: 1649741737000,
          remark: null,
          userIdType: "03"
        },
        {
          id: 233,
          franchiseeName: "小夏",
          withdrawalMobile: null,
          subjectType: 7,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1649747606000,
          updateTime: 1651822376000,
          remark: "\uD83D\uDE01\uD83D\uDE01↓",
          userIdType: "03"
        },
        {
          id: 242,
          franchiseeName: "邱爽",
          withdrawalMobile: null,
          subjectType: 7,
          status: 3,
          msg: null,
          valid: true,
          createTime: 1650436268000,
          updateTime: 1652089728000,
          remark: "13345678901",
          userIdType: null
        }
      ]
    }
  ];

const parsedData = mockData.map((item) => ({ ...item, franchiseesTypeList: item.franchiseesTypeList.slice(0, 3) })).slice(0, 2)
export default parsedData;
